# Documentation on parameters: https://github.com/UBCAgroBot/jetson-ros-workspace/blob/main/src/navigation/README.md

/navigation/mock_camera_publisher:
  ros__parameters:
    video: ''
    verbosity: 30
/navigation/algorithm_publisher:
  ros__parameters:
    alg: 'seesaw'
    mock: True
    show: True
    verbosity: 30
/navigation/post_processor_publisher:
  ros__parameters:
    port: '/dev/ttyACM0'
    verbosity: 20
